language: node_js
node_js:
- 7.10.0
after_success:
- npm run build
- ls
before_deploy:
- cd dist
- ls
deploy:
  provider: npm
  email: nitesh.purohit.it@gmail.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
